# -*- coding: utf-8 -*-
"""add of 2 numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C0PCPyEdJ_rMyD_yaP7WwU5d3EDzTdOh
"""



a=float(input("enter 1st number:"))
b=float(input("enter 2nd number:"))
sum=a*b
print(sum)