# -*- coding: utf-8 -*-
"""area and perimeterog a recatangle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1si6eaiHpoQ3HHZH9wYWk5qZmCijk-Rtm
"""



length = float(input("enter length"))
width=float(input("enter width"))
area=length*width
perimeter=2*(length+width)
print("area:",area)
print("perimeter:",perimeter)